version: '3'

tasks:
  up:
    silent: true
    cmds:
      - docker-compose up -d

  down:
    silent: true
    cmds:
      - docker-compose down

  phpstan:
    silent: true
    cmds:
      - composer phpstan
