version: '3'

tasks:
  up:
    cmds:
      - docker-compose up -d

  down:
    cmds:
      - docker-compose down

  phpstan:
    cmds:
      - ./vendor/bin/phpstan analyse -c phpstan.neon --memory-limit 1G

  pint:
    cmds:
      - ./vendor/bin/pint --config pint.json -v --test

  pint:fix:
    aliases: [fix]
    cmds:
      - ./vendor/bin/pint --config pint.json

  test:
    cmds:
      - php artisan test {{.CLI_ARGS}}

  ci:
    cmds:
      - task: phpstan
      - task: pint
      - task: test
